# Automating Study Area Generation for Expansion Cities

## Model Summary:

This notebook provides a workflow to generate the study area dataset described in the [Study Area definition](../docs/study-areas/README.md).

## Workflow Summary:

The notebook provides a workflow for generating study areas of expansion cities by integrating population data with urban boundary definitions. Rather than relying on administrative boundaries, the target city is selected based on its Functional Urban Area (FUA) boundary, which better reflects actual patterns of human settlement and economic activity. A 1-kilometre buffer is applied around the FUA to avoid discontinuity in setting urban boundaries. The GHS-POP reference grid, which provides a framework enabling interoperability for datasets on deprivation, is clipped to the buffered boundaries of the selected FUA. The result is a harmonised geospatial layer for each expansion city, which can be further analysed for demographic and urban expansion studies.

* **Preprocessing**: Select the target city based on FUA boundaries, which better reflect actual patterns of human settlement and economic activity than administrative boundaries, and load the GHS-POP reference grid.

* **Study Area Definition**: Apply the FUA boundary with a 1-kilometre buffer to ensure spatial continuity.

* **Spatial Clipping**: Clip the population reference grid to the buffered FUA boundary.

* **Outputs**: Export the reference grid of the selected city as GeoPackage and CSV.


### Datasets:
* [Functional Urban Area (FUA)](https://human-settlement.emergency.copernicus.eu/) - the actual urban sprawl and human activities.
* [GHS-POP grid](https://data.jrc.ec.europa.eu/dataset/2ff68a52-5b5b-4a22-8f40-c41da8332cfe) - Global Human Settlement Grid Multitemporal (1975-2030) grid.

In [1]:
# Import Libraries
import geopandas as gpd
import rasterio
from rasterio.mask import mask
from rasterio.features import shapes
from shapely.geometry import mapping, shape, box
import os
import numpy as np
import requests, zipfile, io

In [2]:
data_inputs = '../scripts/data-inputs/'

### Functional Urban Area (FUA)
The FUA was obtained from the Global Human Settlement Layer (GHSL) dataset, which provides spatial data for functional urban areas worldwide.

In [26]:
# Define the URL for the GHS FUA data
url = "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL//GHS_FUA_UCDB2015_GLOBE_R2019A/V1-0/GHS_FUA_UCDB2015_GLOBE_R2019A_54009_1K_V1_0.zip"

# Define the path to the GHS FUA data
path = f"zip+{url}!GHS_FUA_UCDB2015_GLOBE_R2019A_54009_1K_V1_0.gpkg"

GHS_FUA = gpd.read_file(path)

In [27]:
# Select Expansion City
CITY = "Kisumu" # Replace CITY with the name of the city
COUNTRY = "Kenya" # Replace COUNTRY with the name of the country

In [28]:
# Filter FUA for target city
fua_city = GHS_FUA[GHS_FUA["eFUA_name"] == CITY]
fua_city

,eFUA_ID,UC_num,UC_IDs,eFUA_name,Commuting,Cntry_ISO,Cntry_name,FUA_area,UC_area,FUA_p_2015,UC_p_2015,Com_p_2015,geometry
5934,974.0,1.0,4608,Kisumu,1.0,KEN,Kenya,134.0,43.0,369934.301125,308524.08395,61410.217175,"MULTIPOLYGON (((3483000 -2000, 3484000 -2000, ..."

In [29]:
# Create a buffered of the FUA
fua_city_buffered = fua_city.copy()
fua_city_buffered["geometry"] = fua_city_buffered.geometry.buffer(1000, join_style=2) # Buffer by 1000 meters
fua_union = fua_city_buffered.geometry.union_all()

### GHS-POP Reference Grid

**Note:** Directly accessing the GHS-POP reference grid from the remote [URL](https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL/GHS_POP_GLOBE_R2023A/GHS_POP_E2025_GLOBE_R2023A_54009_100/) may be time-consuming due to its large size.  
We recommend downloading the ZIP file locally and subsequently loading the reference grid TIFF file from disk.

In [30]:
GHS_POP = data_inputs + "GHS_POP_E2025_GLOBE_R2023A_54009_100_V1_0.tif"

In [31]:
with rasterio.open(GHS_POP) as pop_raster:

    # Ensure the FUA geometry is in the same CRS as the population raster
    fua_union = gpd.GeoSeries([fua_union], crs=fua_city.crs).to_crs(pop_raster.crs).iloc[0] 
    
    # Mask the population raster with the buffered FUA geometry
    out_image, out_transform = mask(pop_raster, [mapping(fua_union)], crop=True)

    nodata = pop_raster.nodata # keep the nodata value from the original raster
    height, width = out_image.shape[1], out_image.shape[2]
    crs = pop_raster.crs

In [32]:
pixels = []

# Iterate over each column in the raster for the current row
for row in range(height):
    for col in range(width):
        val = out_image[0, row, col] # Extract the pixel value
        if val == nodata:
            continue
        
        # Compute the spatial coordinates of the pixel corners
        minx, maxy = rasterio.transform.xy(out_transform, row, col, offset="ul")
        maxx, miny = rasterio.transform.xy(out_transform, row, col, offset="lr")
        pixel_geom = box(minx, miny, maxx, maxy)

        # Only keep pixels that intersect with the FUA polygon
        if not pixel_geom.intersects(fua_union):
            continue

        pixels.append({"geometry": pixel_geom})

# Convert the list of pixels to a GeoDataFrame
study_area_gdf = gpd.GeoDataFrame(pixels, crs=crs)
study_area_gdf

                                                geometry
0      POLYGON ((3481100 -100, 3481100 0, 3481000 0, ...
1      POLYGON ((3481200 -100, 3481200 0, 3481100 0, ...
2      POLYGON ((3481300 -100, 3481300 0, 3481200 0, ...
3      POLYGON ((3481400 -100, 3481400 0, 3481300 0, ...
4      POLYGON ((3481500 -100, 3481500 0, 3481400 0, ...
...                                                  ...
19795  POLYGON ((3483600 -19000, 3483600 -18900, 3483...
19796  POLYGON ((3483700 -19000, 3483700 -18900, 3483...
19797  POLYGON ((3483800 -19000, 3483800 -18900, 3483...
19798  POLYGON ((3483900 -19000, 3483900 -18900, 3483...
19799  POLYGON ((3484000 -19000, 3484000 -18900, 3483...

[19800 rows x 1 columns]

In [33]:
temp_proj = study_area_gdf.to_crs(epsg=3857)
centroids_4326 = temp_proj.geometry.centroid.to_crs(epsg=4326)

study_area_4326 = study_area_gdf.to_crs(epsg=4326)
study_area_4326["longitude"] = centroids_4326.x
study_area_4326["latitude"]  = centroids_4326.y

bounds = study_area_4326.geometry.bounds
study_area_4326["lon_min"] = bounds.minx
study_area_4326["lon_max"] = bounds.maxx
study_area_4326["lat_min"] = bounds.miny
study_area_4326["lat_max"] = bounds.maxy

study_area_4326

,geometry,longitude,latitude,lon_min,lon_max,lat_min,lat_max
0,"POLYGON ((34.73363 -0.00081, 34.73363 0, 34.73...",34.733131,-0.000404,34.732632,34.733629,-0.000809,0.000000
1,"POLYGON ((34.73463 -0.00081, 34.73463 0, 34.73...",34.734128,-0.000404,34.733629,34.734627,-0.000809,0.000000
2,"POLYGON ((34.73563 -0.00081, 34.73563 0, 34.73...",34.735126,-0.000404,34.734627,34.735625,-0.000809,0.000000
3,"POLYGON ((34.73662 -0.00081, 34.73662 0, 34.73...",34.736124,-0.000404,34.735625,34.736623,-0.000809,0.000000
4,"POLYGON ((34.73762 -0.00081, 34.73762 0, 34.73...",34.737122,-0.000404,34.736623,34.737621,-0.000809,0.000000
...,...,...,...,...,...,...,...
19795,"POLYGON ((34.75865 -0.15367, 34.75865 -0.15286...",34.758152,-0.153262,34.757652,34.758651,-0.153666,-0.152857
19796,"POLYGON ((34.75965 -0.15367, 34.75965 -0.15286...",34.759150,-0.153262,34.758650,34.759649,-0.153666,-0.152857
19797,"POLYGON ((34.76065 -0.15367, 34.76065 -0.15286...",34.760147,-0.153262,34.759648,34.760647,-0.153666,-0.152857
19798,"POLYGON ((34.76164 -0.15367, 34.76164 -0.15286...",34.761145,-0.153262,34.760646,34.761644,-0.153666,-0.152857
19799,"POLYGON ((34.76264 -0.15367, 34.76264 -0.15286...",34.762143,-0.153262,34.761644,34.762642,-0.153666,-0.152857

In [34]:
# Save the study area as a GeoPackage
study_area_4326.to_file(f'../expansion_city/grid-boundary-{CITY.lower()}-4326.gpkg', driver="GPKG")

In [ ]:
# Save the study area as a CSV file without geometry
study_area_4326.drop(columns='geometry').to_csv(f'../grid-boundary-{CITY.lower()}.gpkg', index=False)